services:
  scraperr:
    image: jpyles0524/scraperr:latest
    container_name: scraperr
    command: ["npm", "run", "start"]
    environment:
      # Browser must call the host's port (6161, not 8000)
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      # Inside Docker network, still 8000 (container port)
      - SERVER_URL=http://scraperr_api:8000
    ports:
      - 80:3000
    networks:
      - web

  scraperr_api:
    init: true
    image: jpyles0524/scraperr_api:latest
    environment:
      - LOG_LEVEL=INFO
      - OPENAI_KEY=${OPENAI_KEY}
    container_name: scraperr_api
    ports:
      - 6161:8000
    volumes:
      - /absolute/path/data:/project/app/data
      - /absolute/path/media:/project/app/media
    networks:
      - web

networks:
  web: